### ISSUE TITLE
Erro na configuração do ambiente

### ISSUE THREAD

**Issue by carlosthadeu** [raffaell95/projeto_ope_imobiliaria#10]
Estou querendo conhecer seu projeto, sou iniciante em python e django.

Aconteceu um erro quando estava configurando o ambiente de acordo com as especificações da seção 'Config environment project:'

**ImportError: cannot import name 'login' from 'django.contrib.auth.views'**

**Comment by rg3915** [comment]
@carlosthadeu eu mandei um PR com a correção desse erro, mas basicamente você pode simplesmente remover essa linha. Apesar que você já deve ter resolvido depois desse tempo todo.

https://github.com/raffaell95/projeto_ope_imobiliaria/pull/15

**Comment by raffaell95** [comment]
Boa noite pessoal, desculpas por não responder de imediato é que esse projeto é de faculdade, desde 2019 que não faço nenhuma atualização, vou atualizar algumas libs e lançar as devidas correções.
